### ISSUE TITLE
ERROR ON COMPILING

### ISSUE THREAD

**Issue by HumbleCarl** [mobiten/flutter_phoenix#1]
I tried to run my app with Phoenix attached to it but suddenly the building process cant continue and produces this message

>                                                                         
> Compiler message:                                                       
> ../../../flutter/.pub-cache/hosted/pub.dartlang.org/flutter_phoenix-0.1.0/lib/flutter_phoenix.dart:15:13: Error: The method 'findAncestorStateOfType' isn't defined for the class 'BuildContext'.
>  - 'BuildContext' is from 'package:flutter/src/widgets/framework.dart' ('../../../flutter/packages/flutter/lib/src/widgets/framework.dart').
> Try correcting the name to the name of an existing method, or defining a method named 'findAncestorStateOfType'.
>     context.findAncestorStateOfType<_PhoenixState>().restartApp();

**Comment by MrLepage** [comment]
Hello @HumbleCarl ,

The `findAncestorStateOfType` method has been introduced in Flutter v1.12.0 and replace the `ancestorStateOfType` method which has been deprecated after v1.12.1.

Which version of Flutter are you on?

You may need to update Flutter to a version >=v1.12.0
