### ISSUE TITLE
 dependOnInheritedWidgetOfExactType() or dependOnInheritedElement() was called before _MyAppState.initState() completed.

### ISSUE THREAD

**Issue by abdullah4one** [mobiten/flutter_phoenix#10]
After adding flavor to app showing error when we run it "dependOnInheritedWidgetOfExactType() or dependOnInheritedElement() was called before _MyAppState.initState() completed."
Code from here https://cogitas.net/creating-flavors-of-a-flutter-app/

Error messages "When an inherited widget changes, for example if the value of Theme.of() changes, its dependent widgets are rebuilt. If the dependent widget's reference to the inherited widget is in a constructor or an initState() method, then the rebuilt dependent widget will not reflect the changes in the inherited widget."

 var configuredApp = AppConfig(
    appDisplayName: "Staging",
    env: AppEnv.STAGING,
    child: Phoenix(
      child: MyApp(),
    ),
  );

**Comment by ahmed-Ftkhhar** [comment]
did you figure out the solution?
