### ISSUE TITLE
rebirth not working

### ISSUE THREAD

**Issue by SSebigo** [mobiten/flutter_phoenix#3]
Phoenix.rebirth(context) seems not to work. Maybe it is because I use flutter_bloc as my state management library.

**Comment by Vov4yk** [comment]
Same to me. 

Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, v1.17.4, on Mac OS X 10.15.4 19E287, locale en-UA)
 
[✓] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
[✓] Xcode - develop for iOS and macOS (Xcode 11.5)
[✓] Android Studio (version 4.0)
[✓] Connected device (1 available)

• No issues found!

==========
════════ Exception caught by widgets library ═══════════════════════════════════════════════════════
The following assertion was thrown building IconTheme(color: Color(0xffffffff)):
'package:flutter/src/widgets/navigator.dart': Failed assertion: line 2564 pos 14: 'observer.navigator == null': is not true.


Either the assertion indicates an error in the framework itself, or we should provide substantially more information in this error message to help you determine and fix the underlying cause.
In either case, please report this assertion by filing a bug on GitHub:
  https://github.com/flutter/flutter/issues/new?template=BUG.md

The relevant error-causing widget was: 
  MaterialApp file:///Users/vov4yk/Documents/projects/Flutter/byganet-flutter-app/lib/main.dart:26:12
When the exception was thrown, this was the stack: 
#2      NavigatorState.initState (package:flutter/src/widgets/navigator.dart:2564:14)
#3      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4640:58)
#4      ComponentElement.mount (package:flutter/src/widgets/framework.dart:4476:5)
...     Normal element mounting (214 frames)
#218    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3446:14)
...
════════════════════════════════════════════════════════════════════════════════════════════════════

Also I'm using Bloc, but don't think that can a problem here;
Also I'm using CupertinoTabBar - and it's a candidate to be a problem!

**Comment by hey24sheep** [comment]
Same, Nothing happens on rebirth call. It's like no-op

**Comment by zenkog** [comment]
I got the same issue. It restarts but seems stuck at start up, somehow the app doesn't continue to run.
I'm also using bloc in almost all my pages.

**Comment by NicolasCELLA** [comment]
Same issue 🧐

**Comment by abdullah-almasry** [comment]
Same issue 🧐

**Comment by MrLepage** [comment]
`Phoenix` only rebuild the widget tree beneath him.
If you have any other state related code you want to clear/clean, make sure it is done right after initialization of the root widget beneath `Phoenix`

Please provide some sample code if any of you need more help or guidance :)
