### ISSUE TITLE
onWillPop is not hit after restarting the app using phoenix.rebirth.

### ISSUE THREAD

**Issue by KrunalRGandhi** [mobiten/flutter_phoenix#5]
I am using GlobalKey<NavigatorState> for navigatorKey of MaterialApp. I am using onWillPop on the scaffold of my home page. Before restarting the app using phoenix, Android back button is intercepted by onWillPop and I am able to do my stuff. However after rebirth onWillPop is not hit on Android back button press. Home page is the first page on the navigation stack. 
Any idea what could be the issue?

**Comment by MrLepage** [comment]
Not really without seeing some code..
You probably have found your issue as of now...
