### ISSUE TITLE
Allow accessing phoenix via (global) key

### ISSUE THREAD

**Issue by point-source** [mobiten/flutter_phoenix#6]
In the case that a developer is building an app with redux state management, he/she may want to call phoenix from an action which does not have clear access to widget context. In this case, it may be useful to access it via global key.

**Comment by themightychris** [comment]
I'm trying to call `rebirth()` from a message handler under flutter_driver, and similarly don't have access to a build context there

**Comment by MrLepage** [comment]
Will add a `key` parameter in the next version.
