### ISSUE TITLE
Black screen

### ISSUE THREAD

**Issue by erperejildo** [mobiten/flutter_phoenix#9]
When I run `Phoenix.rebirth(context);` but I see a black screen for a few seconds

**Comment by MrLepage** [comment]
Phoenix rebuild the entire widget tree beneath him.
This is the only thing it does.

Make sure you do not have any initialization code that prevents your UI do be displayed after a `rebirth`

**Comment by desmeit** [comment]
I have this issue as well.

**Comment by minhdanh** [comment]
I'm seeing this behavior too. Can we at least change the color of the black screen while Pheonix rebuilding the widget tree?
